config/routes.rb
Rails.application.routes.draw do
#  GET /about
 get "about-us", to: "about#index", as: :about
 get "sign-up", to: "registation#new"
 post "sign-up", to: "registation#create"

 root to:"main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# email:string
#password:string_digest
#password:string virtual
#password_confirmation:string virtual

class User < ApplicationRecord
    has_secure_password
    
    validates :email, presence: true, format: {with:/\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}
end

app/controllers/about_controller.rb
class AboutController<ApplicationController 
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController<ApplicationController
    def index
    end
end

app/controllers/registation_controller.rb
class RegistationController < ApplicationController
    def new
        @user = User.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About US</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial:"shared/navbar" %>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
<h1>Welcome to Scheduled tweets</h1>
</div>

app/views/registation/new.html.erb
<h1>Sign Up</h1>
<%= form_with model: @user, url: sign_up_path do |form| %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "saduni@gmail.com" %>
    </div>
    <div class="mb-3">
        <%= form.label :password%>
        <%= form.password_field :password, class: "form-control", placeholder: "password" %>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
    </div>
    <div class="mb-3">
        <%= form.submit "Sign Up", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>